Repository pagopa/pagopa-ecommerce-watchdog-deadletter-service, pull requests merged in 2025-09, with the labels that each got.

#1 docs: add CODEOWNERS file
  CODEOWNERS
Labels: documentation, size/small, ignore-for-release, skip-release

#2 Update initial configuration documentation
  .env.example
  .sdkmanrc
  README.md
Labels: documentation, size/small, ignore-for-release, skip-release

#4 fix(build): PIDM-973 apply spotless
  src/main/kotlin/it/pagopa/ecommerce/watchdog/deadletter/controllers/WatchdogDeadletterController.kt
Labels: size/small, ignore-for-release, skip-release

#6 [PIDM-978] Add ecommerce helpdesk mock
  .env.example
  .gitignore
  README.md
  docker-compose.yml
  docker/ecommerce-helpdesk-mock/Dockerfile.helpdesk-mock
  docker/ecommerce-helpdesk-mock/helpdesk.json
  docker/ecommerce-helpdesk-mock/middleware.js
  docker/ecommerce-helpdesk-mock/routes.json
Labels: enhancement, size/small, ignore-for-release, skip-release

#8 PIDM-987 Creation first version of the helm settings
  .devops/azure-templates/api-tests.yml
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .env.example
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/valuesOverrides/overrides-jvm-dev.yaml
Labels: enhancement, ignore-for-release, skip-release, size/large
